name: Generate Contribution Snake

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Generate Snake
    - name: Generate Snake Image
      run: python generate-snake.py

    # Commit and push the generated images to the output branch
    - name: Commit and Push Images
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "GitHub Actions"
        author_email: "github-actions@github.com"
        message: "Add contribution snake images"
        add: "dist/*"
