name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v1.3
        with:
          github_user_name: Darkwarrior247  # GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg  # Path to save the SVG image
          gif_out_path: dist/github-contribution-grid-snake.gif  # (Optional) If you want a GIF as well
